name: Bump version and create changelog with commitizen

on:
  workflow_call:

jobs:
  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
#    runs-on: self-hosted
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Temporarily disable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access_token: ${{ secrets.GH_DX_CI }}
          branch: ${{ github.event.repository.default_branch }}
          enforce_admins: false
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          git_name: commitizen-action[bot]
          changelog_increment_filename: body.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access_token: ${{ secrets.GH_DX_CI }}
          branch: ${{ github.event.repository.default_branch }}
          enforce_admins: true
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.cz.outputs.version }}
          body_path: body.md
          token: ${{ secrets.GITHUB_TOKEN }}
